@Workflow.Web.Api_HostAddress = http://localhost:5278

GET {{Workflow.Web.Api_HostAddress}}/api/priority
Accept: application/json

###
GET {{Workflow.Web.Api_HostAddress}}/api/tasks/00000000-0000-0000-0000-000000000000
Accept: application/json

###
POST {{Workflow.Web.Api_HostAddress}}/api/tasks
Content-Type: application/json

{
  "Name": "trabajar en api",
  "Description": "reañizar trabajos demtro del proyecto de API Workflow",
  "StateCode": 1,
  "PriorityCode": 1
}
