@Workflow.Web.Api_HostAddress = http://localhost:5278

GET {{Workflow.Web.Api_HostAddress}}/api/priority
Accept: application/json

###
GET {{Workflow.Web.Api_HostAddress}}/api/state
Accept: application/json

###
GET {{Workflow.Web.Api_HostAddress}}/api/tasks/59BDE736-0471-4BC3-A108-2A815B8AD5B6
Accept: application/json

###
POST {{Workflow.Web.Api_HostAddress}}/api/tasks
Content-Type: application/json

{
  "Name": "trabajar en api",
  "Description": "reañizar trabajos demtro del proyecto de API Workflow",
  "StateCode": 1,
  "PriorityCode": 1
}

###
PUT {{Workflow.Web.Api_HostAddress}}/api/tasks/59BDE736-0471-4BC3-A108-2A815B8AD5B6
Content-Type: application/json

{
  "Name": "trabajar en api 2",
  "Description": "hola"
}

###
DELETE {{Workflow.Web.Api_HostAddress}}/api/tasks/59BDE736-0471-4BC3-A108-2A815B8AD5B6
Accept: application/json
